### ISSUE TITLE
sunstone depends on libcurl.so.4

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/packages#120]
Hi, I was built opennebula packages with `BUILD_COMPONENTS='rubygems'`, but after install sunstone throws an error:
```
--------------------------------------
         Server configuration         
--------------------------------------
{:auth=>"opennebula",
 :core_auth=>"cipher",
 :debug_level=>3,
 :env=>"prod",
 :host=>"0.0.0.0",
 :keep_me_logged=>true,
 :lang=>"en_US",
 :marketplace_url=>"http://marketplace.opennebula.systems/",
 :memcache_host=>"opennebula-opennebula-memcached",
 :memcache_namespace=>"opennebula.sunstone",
 :memcache_port=>11211,
 :mode=>"mixed",
 :one_xmlrpc=>"http://opennebula-opennebula-oned:2633/RPC2",
 :one_xmlrpc_timeout=>60,
 :oneflow_server=>"http://opennebula-opennebula-flow:2474/",
 :port=>9869,
 :remote_version=>"http://downloads.opennebula.org/latest",
 :routes=>["oneflow", "support"],
 :sessions=>"memcache",
 :table_order=>"desc",
 :tmpdir=>"/var/tmp",
opennebula-opennebula-memcached:11211
 :two_factor_auth_issuer=>"opennebula",
 :vnc_proxy_cert=>nil,
 :vnc_proxy_ipv6=>false,
 :vnc_proxy_key=>nil,
 :vnc_proxy_port=>29876,
 :vnc_proxy_support_wss=>false,
 :vnc_request_password=>false,
 :session_expire_time=>3600}
--------------------------------------
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libcurl.so.4: cannot open shared object file: No such file or directory - /usr/share/one/gems-dist/gems/curb-0.9.10/lib/curb_core.so (LoadError)
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/share/one/gems-dist/gems/curb-0.9.10/lib/curl.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/share/one/gems-dist/gems/curb-0.9.10/lib/curb.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/one/sunstone/routes/support.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/one/sunstone/sunstone-server.rb:569:in `block in <main>'
        from /usr/lib/one/sunstone/sunstone-server.rb:568:in `each'
        from /usr/lib/one/sunstone/sunstone-server.rb:568:in `<main>'
```

**Comment by kvaps** [comment]
My distro is ubuntu18.04, solved by manually installing `libcurl4`.

**Comment by vholer** [comment]
Perfect, thank you! I have added missing deps on libcurl.
