### ISSUE TITLE
Add less to opennebula-cli dependencies

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/packages#51]
Otherwise you can have a next error:
```
Traceback (most recent call last):
        10: from /usr/bin/oneimage:34:in `<main>'
         9: from /usr/bin/oneimage:34:in `new'
         8: from /usr/lib/one/ruby/cli/command_parser.rb:84:in `initialize'
         7: from /usr/lib/one/ruby/cli/command_parser.rb:457:in `run'
         6: from /usr/bin/oneimage:368:in `block (2 levels) in <main>'
         5: from /usr/lib/one/ruby/cli/one_helper.rb:756:in `list_pool'
         4: from /usr/lib/one/ruby/cli/one_helper.rb:598:in `list_pool_table'
         3: from /usr/lib/one/ruby/cli/one_helper.rb:520:in `start_pager'
         2: from /usr/lib/one/ruby/cli/one_helper.rb:520:in `fork'
         1: from /usr/lib/one/ruby/cli/one_helper.rb:528:in `block in start_pager'
/usr/lib/one/ruby/cli/one_helper.rb:528:in `exec': No such file or directory - less (Errno::ENOENT)
```

**Comment by vholer** [comment]
I have added note about missing `less` runtime detection into issue related to the CLI paging https://github.com/OpenNebula/one/issues/2565.
